name: manga-reader
services:
    server:
        build:
            context: .
            dockerfile: ./Dockerfile
        restart: unless-stopped
        volumes:
            - ./logs:/app/logs
        environment:
            - DB_USER=admin
            - DB_PASSWORD=secret
            - DB_HOST=database:5432
            - DB_NAME=manga_reader
        ports:
            - "8000:8000"
        networks:
            - manga-reader

    database:
        image: postgres:latest
        container_name: database
        restart: unless-stopped
        environment:
            - POSTGRES_USER=admin
            - POSTGRES_PASSWORD=secret
            - POSTGRES_DB=manga_reader
        volumes:
            - ./db:/var/lib/postgresql/data
        networks:
            - manga-reader

networks:
  manga-reader:
    name: manga-reader
    driver: bridge